version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: microservicios_db
      MYSQL_USER: ms_user
      MYSQL_PASSWORD: ms_pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8081"
    restart: unless-stopped

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8081"
    depends_on:
      - eureka-server
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8081"
    depends_on:
      - eureka-server
      - config-server
    restart: unless-stopped

  user-app:
    build:
      context: ./user-app
    container_name: user-app
    ports:
      - "8082:8081"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    restart: unless-stopped

  ubicacion-service:
    build:
      context: ./ubicacion-service
    container_name: ubicacion-service
    ports:
      - "8083:8081"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    restart: unless-stopped

  email-service:
    build:
      context: ./email-service
    container_name: email-service
    ports:
      - "8084:8081"
    depends_on:
      - eureka-server
      - config-server
    restart: unless-stopped

  oauth-server:
    build:
      context: ./oauth-server
    container_name: oauth-server
    ports:
      - "8085:8081"
    depends_on:
      - eureka-server
      - config-server
    restart: unless-stopped

networks:
  default:
    driver: bridge
